### basic settings

# site properties and page defaults
title: WANG LAB
subtitle: Non-invasive Lineage Tracing from DNA Methylation
description: ''
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  email: wangshouwen@westlake.edu.cn
  google-scholar: https://scholar.google.com.hk/citations?user=76hxR58AAAAJ&hl=en
  github: ShouWenWang-Lab
  twitter: ShouwenW
  youtube: channel/UCr5rqY3-FstBCWBT_ogCqYg

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
